theme: jekyll-theme-cayman
title: Plasma Turbulence
description: Animations, figures, and additional information to accompany my poster presentation at the 2019 Mid-Michigan Symposium for Undergraduate Research Experiences
